// <auto-generated />
using Eindwerk.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Eindwerk.Migrations
{
    [DbContext(typeof(EindwerkContext))]
    [Migration("20180419090250_initial migration")]
    partial class initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Eindwerk.Models.Aanvraag", b =>
                {
                    b.Property<int>("AanvraagId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("EindDatum");

                    b.Property<string>("Omschrijving");

                    b.Property<DateTime>("StartDatum");

                    b.Property<string>("Titel");

                    b.HasKey("AanvraagId");

                    b.ToTable("Aanvraag");
                });
#pragma warning restore 612, 618
        }
    }
}
